### ISSUE TITLE
Add prometheus plugin

### ISSUE THREAD

**Issue by JorritSalverda** [pires/docker-elasticsearch-kubernetes#33]
I inherit this docker image and add the prometheus plugin from https://github.com/vvanholl/elasticsearch-prometheus-exporter/ to visualize all ES stats using the following dashboard https://grafana.net/dashboards/266.

What do you think about adding it to your container?

**Comment by pires** [comment]
The problem with adding plug-ins to this image is that they can't be made optional. In this case, what happens when people don't have Prometheus in place? It just becomes a waste of disk space, etc. My suggestion is to use this image as a base image to your own image, where you add the plug-ins you need.

**Comment by JorritSalverda** [comment]
No worries, I have it in my own inherited container.
